require('dotenv').config()

const mongoose = require('mongoose')
const Course = require('../models/Course')

const courses = [
  {
    title: 'Frontend',
    description: 'Изучение современной frontend-разработки от HTML до React.',
    category: 'it',
    courseKey: 'frontend',
    icon: '💻',
    roadmap: [
      'HTML и семантика',
      'CSS и адаптивность',
      'JavaScript',
      'DOM и события',
      'React',
      'Состояние и props',
      'Компонентный подход',
      'Формы и валидация',
      'Работа с API',
      'Итоговый проект',
    ],
    technologies: ['HTML', 'CSS', 'JavaScript', 'React', 'Vite', 'Tailwind CSS'],
    lessons: [
      {
        lessonId: 'frontend-1',
        title: 'HTML основы',
        description: 'Структура страницы и базовые теги.',
        content: '<p>HTML задаёт структуру сайта: заголовки, абзацы, списки, ссылки, изображения и формы.</p>',
        example: '<h1>Мой сайт</h1>',
        task: { type: 'input', question: 'Какой тег используется для самого главного заголовка?', answer: 'h1', options: [] },
      },
      {
        lessonId: 'frontend-2',
        title: 'CSS основы',
        description: 'Цвета, отступы и оформление страницы.',
        content: '<p>CSS отвечает за внешний вид: цвета, размеры, отступы, выравнивание и адаптивность интерфейса.</p>',
        example: 'body { color: #111827; }',
        task: { type: 'input', question: 'Какое CSS-свойство меняет цвет текста?', answer: 'color', options: [] },
      },
      {
        lessonId: 'frontend-3',
        title: 'Flexbox',
        description: 'Выравнивание элементов по строке и колонке.',
        content: '<p>Flexbox помогает удобно выравнивать блоки по горизонтали и вертикали и управлять расстояниями между ними.</p>',
        example: '.wrapper { display: flex; justify-content: center; }',
        task: {
          type: 'multiple',
          question: 'Какое свойство включает flex-контейнер?',
          answer: 'display: flex',
          options: ['display: block', 'display: flex', 'position: flex'],
        },
      },
      {
        lessonId: 'frontend-4',
        title: 'JavaScript переменные',
        description: 'let, const и основы логики.',
        content: '<p>JavaScript добавляет логику и интерактивность: переменные, условия, циклы и функции.</p>',
        example: 'const name = "Ali"',
        task: { type: 'multiple', question: 'Что лучше использовать для неизменяемой переменной?', answer: 'const', options: ['var', 'const', 'style'] },
      },
      {
        lessonId: 'frontend-5',
        title: 'Условия и сравнения',
        description: 'if, else и логические проверки.',
        content: '<p>Условия помогают программе принимать решения в зависимости от данных пользователя или состояния интерфейса.</p>',
        example: 'if (age > 18) { console.log("OK") }',
        task: { type: 'input', question: 'Какое ключевое слово используется для условия в JavaScript?', answer: 'if', options: [] },
      },
      {
        lessonId: 'frontend-6',
        title: 'DOM и события',
        description: 'Работа с кнопками и элементами на странице.',
        content: '<p>Через DOM JavaScript получает доступ к элементам страницы и может реагировать на клики и ввод.</p>',
        example: "button.addEventListener('click', handleClick)",
        task: { type: 'multiple', question: 'Как называется событие нажатия на кнопку?', answer: 'click', options: ['hover', 'click', 'input'] },
      },
      {
        lessonId: 'frontend-7',
        title: 'React компоненты',
        description: 'Создание переиспользуемых интерфейсных блоков.',
        content: '<p>React строит интерфейс из компонентов. Каждый компонент отвечает за отдельную часть UI.</p>',
        example: 'function Card() { return <div>Card</div> }',
        task: { type: 'multiple', question: 'Основная идея React?', answer: 'Компоненты', options: ['Компоненты', 'Только стили', 'Только базы данных'] },
      },
      {
        lessonId: 'frontend-8',
        title: 'State и props',
        description: 'Передача данных и управление состоянием.',
        content: '<p>Props передают данные в компонент, а state хранит изменяемые данные внутри компонента.</p>',
        example: 'const [count, setCount] = useState(0)',
        task: { type: 'input', question: 'Что хранит изменяемые данные внутри React-компонента?', answer: 'state', options: [] },
      },
      {
        lessonId: 'frontend-9',
        title: 'Формы и поля ввода',
        description: 'Работа с input и отправкой форм.',
        content: '<p>Формы собирают данные пользователя, а контролируемые поля в React помогают их валидировать и отправлять.</p>',
        example: '<input value={name} onChange={handleChange} />',
        task: { type: 'multiple', question: 'Какой тег используется для поля ввода?', answer: 'input', options: ['form', 'span', 'input'] },
      },
      {
        lessonId: 'frontend-10',
        title: 'Работа с API',
        description: 'Загрузка данных с сервера.',
        content: '<p>Frontend может запрашивать данные у backend через fetch или axios и отображать их на экране.</p>',
        example: "fetch('/api/courses')",
        task: { type: 'input', question: 'Как называется обмен данными между frontend и backend через запросы?', answer: 'api', options: [] },
      },
    ],
    quiz: [],
  },
  {
    title: 'Backend',
    description: 'Изучение серверной разработки, API и работы с данными.',
    category: 'it',
    courseKey: 'backend',
    icon: '⚙️',
    roadmap: [
      'Что такое backend',
      'HTTP и запросы',
      'Express',
      'Роуты',
      'Middleware',
      'REST API',
      'JWT и авторизация',
      'Валидация',
      'Ошибки сервера',
      'Подключение базы',
    ],
    technologies: ['Node.js', 'Express', 'MongoDB', 'JWT', 'REST API'],
    lessons: [
      {
        lessonId: 'backend-1',
        title: 'Что делает backend',
        description: 'Роль сервера в приложении.',
        content: '<p>Backend принимает запросы, обрабатывает данные, работает с базой и отдаёт ответ клиенту.</p>',
        example: "app.get('/api/health', (req, res) => res.json({ ok: true }))",
        task: { type: 'multiple', question: 'Что делает backend?', answer: 'Обрабатывает запросы и данные', options: ['Рисует кнопки', 'Обрабатывает запросы и данные', 'Только включает тему'] },
      },
      {
        lessonId: 'backend-2',
        title: 'HTTP методы',
        description: 'GET, POST, PUT, DELETE.',
        content: '<p>HTTP-методы показывают, что мы хотим сделать с данными: получить, создать, обновить или удалить.</p>',
        example: 'GET /api/users',
        task: { type: 'input', question: 'Какой метод чаще всего используют для создания данных?', answer: 'post', options: [] },
      },
      {
        lessonId: 'backend-3',
        title: 'Express и сервер',
        description: 'Создание сервера на Express.',
        content: '<p>Express помогает быстро создавать сервер, маршруты и middleware в Node.js.</p>',
        example: 'const app = express()',
        task: { type: 'input', question: 'Какой популярный framework часто используют с Node.js для сервера?', answer: 'express', options: [] },
      },
      {
        lessonId: 'backend-4',
        title: 'Маршруты',
        description: 'Организация endpoint-ов.',
        content: '<p>Роуты определяют, какая функция должна отвечать на конкретный URL и HTTP-метод.</p>',
        example: "router.get('/courses', getCourses)",
        task: { type: 'multiple', question: 'Что задаёт роут?', answer: 'Какой обработчик отвечает на URL', options: ['Цвет кнопки', 'Какой обработчик отвечает на URL', 'Шрифт проекта'] },
      },
      {
        lessonId: 'backend-5',
        title: 'Middleware',
        description: 'Промежуточная логика запросов.',
        content: '<p>Middleware запускается до основного обработчика и часто используется для auth, логов и парсинга данных.</p>',
        example: 'app.use(express.json())',
        task: { type: 'multiple', question: 'Для чего часто нужен middleware?', answer: 'Проверка и подготовка запроса', options: ['Рисование UI', 'Проверка и подготовка запроса', 'Создание CSS'] },
      },
      {
        lessonId: 'backend-6',
        title: 'REST API',
        description: 'Работа с ресурсами приложения.',
        content: '<p>REST API помогает структурировать работу с ресурсами приложения: пользователи, курсы, уроки и другие сущности.</p>',
        example: 'POST /api/courses',
        task: { type: 'input', question: 'Как называется популярный подход к построению API по ресурсам?', answer: 'rest', options: [] },
      },
      {
        lessonId: 'backend-7',
        title: 'JWT',
        description: 'Токены авторизации.',
        content: '<p>JWT используется для аутентификации: сервер создаёт токен, клиент хранит его и отправляет в запросах.</p>',
        example: "Authorization: Bearer <token>",
        task: { type: 'input', question: 'Как называется токен, который часто используют для авторизации API?', answer: 'jwt', options: [] },
      },
      {
        lessonId: 'backend-8',
        title: 'Валидация данных',
        description: 'Проверка входящих полей.',
        content: '<p>Сервер должен проверять email, пароль, обязательные поля и корректность данных до сохранения.</p>',
        example: "if (!email) return res.status(400).json({ error: 'Email required' })",
        task: { type: 'multiple', question: 'Зачем нужна валидация?', answer: 'Чтобы не сохранять неправильные данные', options: ['Чтобы не сохранять неправильные данные', 'Чтобы сделать тёмную тему', 'Чтобы ускорить мышку'] },
      },
      {
        lessonId: 'backend-9',
        title: 'Обработка ошибок',
        description: 'Корректные ответы при сбоях.',
        content: '<p>Нужно возвращать понятные коды ошибок и сообщения, а детали сбоев логировать отдельно.</p>',
        example: "res.status(500).json({ error: 'Server error' })",
        task: { type: 'multiple', question: 'Какой код обычно отправляют при внутренней ошибке сервера?', answer: '500', options: ['200', '301', '500'] },
      },
      {
        lessonId: 'backend-10',
        title: 'Подключение MongoDB',
        description: 'Работа backend с базой данных.',
        content: '<p>Сервер подключается к MongoDB, сохраняет документы, получает коллекции и обновляет записи.</p>',
        example: 'mongoose.connect(MONGODB_URI)',
        task: { type: 'input', question: 'Как называется библиотека, которую часто используют для MongoDB в Node.js?', answer: 'mongoose', options: [] },
      },
    ],
    quiz: [],
  },
  {
    title: 'Database',
    description: 'Изучение SQL, NoSQL и проектирования баз данных.',
    category: 'it',
    courseKey: 'database',
    icon: '🗄️',
    roadmap: [
      'Что такое база данных',
      'Таблицы и записи',
      'SQL SELECT',
      'INSERT и UPDATE',
      'Первичный ключ',
      'Связи таблиц',
      'JOIN',
      'Индексы',
      'Транзакции',
      'NoSQL',
    ],
    technologies: ['MySQL', 'PostgreSQL', 'MongoDB', 'Redis'],
    lessons: [
      {
        lessonId: 'database-1',
        title: 'Что такое база данных',
        description: 'Основы хранения данных.',
        content: '<p>База данных хранит информацию приложения и позволяет быстро получать и изменять нужные данные.</p>',
        example: 'users, courses, lessons',
        task: { type: 'multiple', question: 'Для чего нужна база данных?', answer: 'Для хранения и получения данных', options: ['Для хранения и получения данных', 'Для рисования иконок', 'Для смены темы'] },
      },
      {
        lessonId: 'database-2',
        title: 'Таблицы и строки',
        description: 'Как устроены реляционные базы.',
        content: '<p>В реляционных БД данные хранятся в таблицах, строках и столбцах.</p>',
        example: 'users(id, name, email)',
        task: { type: 'input', question: 'Как называется вертикальная часть таблицы в БД?', answer: 'column', options: [] },
      },
      {
        lessonId: 'database-3',
        title: 'SELECT',
        description: 'Получение данных из таблицы.',
        content: '<p>SELECT используется для чтения записей из таблицы.</p>',
        example: 'SELECT * FROM users;',
        task: { type: 'input', question: 'Какое SQL-слово используют для получения данных?', answer: 'select', options: [] },
      },
      {
        lessonId: 'database-4',
        title: 'INSERT',
        description: 'Добавление записей.',
        content: '<p>INSERT создаёт новые записи в таблице.</p>',
        example: "INSERT INTO users(name) VALUES('Ali');",
        task: { type: 'multiple', question: 'Какой SQL-запрос добавляет новые данные?', answer: 'INSERT', options: ['INSERT', 'DROP', 'SELECT'] },
      },
      {
        lessonId: 'database-5',
        title: 'UPDATE',
        description: 'Изменение существующих данных.',
        content: '<p>UPDATE используется для изменения уже существующих записей.</p>',
        example: "UPDATE users SET name='Omar' WHERE id=1;",
        task: { type: 'input', question: 'Какой запрос изменяет существующие записи?', answer: 'update', options: [] },
      },
      {
        lessonId: 'database-6',
        title: 'PRIMARY KEY',
        description: 'Уникальный идентификатор записи.',
        content: '<p>Первичный ключ помогает однозначно определить каждую запись в таблице.</p>',
        example: 'id INT PRIMARY KEY',
        task: { type: 'multiple', question: 'Что делает PRIMARY KEY?', answer: 'Уникально определяет запись', options: ['Меняет цвет таблицы', 'Уникально определяет запись', 'Удаляет все записи'] },
      },
      {
        lessonId: 'database-7',
        title: 'Связи таблиц',
        description: 'One-to-many и другие связи.',
        content: '<p>Связи позволяют соединять пользователей, курсы, уроки и другие сущности между собой.</p>',
        example: 'user_id -> users.id',
        task: { type: 'multiple', question: 'Что связывает таблицы между собой?', answer: 'Ключи и связи', options: ['Стили', 'Ключи и связи', 'Изображения'] },
      },
      {
        lessonId: 'database-8',
        title: 'JOIN',
        description: 'Объединение данных из нескольких таблиц.',
        content: '<p>JOIN объединяет данные из нескольких связанных таблиц в одном запросе.</p>',
        example: 'SELECT * FROM users JOIN courses ON users.id = courses.user_id;',
        task: { type: 'input', question: 'Какое SQL-слово объединяет таблицы?', answer: 'join', options: [] },
      },
      {
        lessonId: 'database-9',
        title: 'Индексы',
        description: 'Ускорение поиска данных.',
        content: '<p>Индексы помогают находить данные быстрее в больших таблицах.</p>',
        example: 'CREATE INDEX idx_email ON users(email);',
        task: { type: 'multiple', question: 'Зачем нужны индексы?', answer: 'Чтобы ускорять поиск', options: ['Чтобы ускорять поиск', 'Чтобы делать UI красивее', 'Чтобы менять пароль'] },
      },
      {
        lessonId: 'database-10',
        title: 'NoSQL',
        description: 'Документные базы данных.',
        content: '<p>NoSQL БД, например MongoDB, хорошо подходят для гибких структур данных.</p>',
        example: "{ name: 'Ali', skills: ['JS', 'Node'] }",
        task: { type: 'input', question: 'Какая популярная документная база используется в этом проекте?', answer: 'mongodb', options: [] },
      },
    ],
    quiz: [],
  },
  {
    title: 'Английский',
    description: 'Изучение английского языка с уроками и тестом на уровень.',
    category: 'language',
    courseKey: 'english',
    icon: '🇬🇧',
    roadmap: ['Приветствия', 'Числа', 'Семья', 'Вопросы', 'Базовая грамматика'],
    technologies: ['Vocabulary', 'Grammar', 'Speaking'],
    lessons: [
      {
        lessonId: 'english-1',
        title: 'Основы приветствий',
        description: 'Базовые фразы для знакомства и приветствия.',
        content: '<p>В английском языке приветствия очень важны. Начнём с простых фраз: Hello, Hi, Good morning.</p>',
        example: 'Hello! How are you?',
        task: { type: 'input', question: 'Как переводится слово "Hello"?', answer: 'привет', options: [] },
      },
      {
        lessonId: 'english-2',
        title: 'Числа и время',
        description: 'Базовые числительные и счёт.',
        content: '<p>Числа помогают говорить о времени, возрасте, количестве и датах.</p>',
        example: 'One, two, three...',
        task: { type: 'multiple', question: 'Какое число идёт после five?', answer: 'Six', options: ['Four', 'Six', 'Seven', 'Nine'] },
      },
      {
        lessonId: 'english-3',
        title: 'Семья и родственники',
        description: 'Как рассказать о семье.',
        content: '<p>Слова mother, father, brother, sister нужны, чтобы говорить о близких людях.</p>',
        example: 'My brother is a student.',
        task: { type: 'input', question: 'Как будет "брат" по-английски?', answer: 'brother', options: [] },
      },
    ],
    quiz: [
      { question: 'What is the capital of the United Kingdom?', options: ['London', 'Paris', 'Berlin', 'Madrid'], correctIndex: 0 },
      { question: 'How do you say "Hello" in English?', options: ['Hola', 'Bonjour', 'Hello', 'Ciao'], correctIndex: 2 },
      { question: 'What is the past tense of "go"?', options: ['went', 'gone', 'going', 'goes'], correctIndex: 0 },
      { question: 'Which word is a color?', options: ['Apple', 'Blue', 'Run', 'Big'], correctIndex: 1 },
      { question: 'What is the plural of "child"?', options: ['Childs', 'Children', 'Childes', 'Childrens'], correctIndex: 1 },
      { question: 'Choose the correct sentence:', options: ['I am student', 'I student am', 'Am I student', 'I am a student'], correctIndex: 3 },
      { question: 'What does "happy" mean?', options: ['Sad', 'Angry', 'Joyful', 'Tired'], correctIndex: 2 },
      { question: 'Which is a question word?', options: ['And', 'What', 'But', 'Or'], correctIndex: 1 },
      { question: 'What is the opposite of "hot"?', options: ['Cold', 'Warm', 'Big', 'Small'], correctIndex: 0 },
      { question: 'How many days are in a week?', options: ['5', '6', '7', '8'], correctIndex: 2 },
    ],
  },
  {
    title: 'Арабский',
    description: 'Изучение арабского языка с базовыми уроками и тестом.',
    category: 'language',
    courseKey: 'arabic',
    icon: '🇸🇦',
    roadmap: ['Алфавит', 'Числа', 'Фразы', 'Базовые слова', 'Практика чтения'],
    technologies: ['Alphabet', 'Reading', 'Speaking'],
    lessons: [
      {
        lessonId: 'arabic-1',
        title: 'Арабский алфавит',
        description: 'Первые буквы и направление письма.',
        content: '<p>Арабский язык пишется справа налево и состоит из 28 букв.</p>',
        example: 'ا ب ت',
        task: { type: 'input', question: 'Напишите первую букву арабского алфавита.', answer: 'ا', options: [] },
      },
      {
        lessonId: 'arabic-2',
        title: 'Числа в арабском',
        description: 'Базовые цифры и числа.',
        content: '<p>Числа нужны для счёта, времени и разговорной речи.</p>',
        example: '1 - واحد, 2 - اثنان',
        task: { type: 'multiple', question: 'Как будет число 2?', answer: 'اثنان', options: ['واحد', 'اثنان', 'ثلاثة', 'أربعة'] },
      },
      {
        lessonId: 'arabic-3',
        title: 'Повседневные фразы',
        description: 'Приветствие и благодарность.',
        content: '<p>Простые повседневные фразы помогают начать разговор и понимать базовые ответы.</p>',
        example: 'شكراً',
        task: { type: 'input', question: 'Как на арабском будет "спасибо"?', answer: 'شكراً', options: [] },
      },
    ],
    quiz: [
      { question: 'Как сказать "привет" на арабском?', options: ['مرحبا', 'Hello', 'Bonjour', 'Ciao'], correctIndex: 0 },
      { question: 'Какой алфавит используется в арабском?', options: ['Латинский', 'Кириллица', 'Арабский', 'Иероглифы'], correctIndex: 2 },
      { question: 'Как сказать "спасибо" на арабском?', options: ['شكراً', 'Thank you', 'Merci', 'Grazie'], correctIndex: 0 },
      { question: 'Какое число "один" на арабском?', options: ['واحد', 'اثنان', 'ثلاثة', 'أربعة'], correctIndex: 0 },
      { question: 'Как сказать "да" на арабском?', options: ['لا', 'نعم', 'ربما', 'أبداً'], correctIndex: 1 },
      { question: 'Какой цвет "синий" на арабском?', options: ['أحمر', 'أزرق', 'أخضر', 'أصفر'], correctIndex: 1 },
      { question: 'Как сказать "вода" на арабском?', options: ['ماء', 'خبز', 'لحم', 'فواكه'], correctIndex: 0 },
      { question: 'Какое время суток "утро"?', options: ['صباح', 'مساء', 'ليل', 'ظهر'], correctIndex: 0 },
      { question: 'Как сказать "школа" на арабском?', options: ['مدرسة', 'جامعة', 'مكتب', 'منزل'], correctIndex: 0 },
      { question: 'Какое животное "кошка"?', options: ['كلب', 'قطة', 'خيل', 'بقرة'], correctIndex: 1 },
    ],
  },
  {
    title: 'Русский',
    description: 'Изучение русского языка с уроками и тестом.',
    category: 'language',
    courseKey: 'russian',
    icon: '🇷🇺',
    roadmap: ['Алфавит', 'Существительные', 'Глаголы', 'Речь', 'Грамматика'],
    technologies: ['Grammar', 'Reading', 'Speaking'],
    lessons: [
      {
        lessonId: 'russian-1',
        title: 'Русский алфавит',
        description: 'Кириллица и основные буквы.',
        content: '<p>Русский алфавит основан на кириллице и включает 33 буквы.</p>',
        example: 'А Б В Г Д',
        task: { type: 'input', question: 'Напишите первую букву русского алфавита.', answer: 'а', options: [] },
      },
      {
        lessonId: 'russian-2',
        title: 'Род существительных',
        description: 'Мужской, женский и средний род.',
        content: '<p>Существительные в русском языке имеют род, который влияет на согласование слов.</p>',
        example: 'стол, книга, окно',
        task: { type: 'multiple', question: 'Какой род у слова "солнце"?', answer: 'Средний', options: ['Мужской', 'Женский', 'Средний'] },
      },
      {
        lessonId: 'russian-3',
        title: 'Времена глаголов',
        description: 'Настоящее, прошедшее и будущее.',
        content: '<p>Глаголы меняются по временам и помогают передавать, когда происходит действие.</p>',
        example: 'иду, шёл, буду идти',
        task: { type: 'input', question: 'Напишите прошедшее время глагола "идти".', answer: 'шел', options: [] },
      },
    ],
    quiz: [
      { question: 'Какой падеж используется для объекта действия?', options: ['Именительный', 'Винительный', 'Родительный', 'Дательный'], correctIndex: 1 },
      { question: 'Как сказать "спасибо" на русском?', options: ['Please', 'Thank you', 'Спасибо', 'Merci'], correctIndex: 2 },
      { question: 'Какой род у слова "дом"?', options: ['Женский', 'Мужской', 'Средний', 'Нет рода'], correctIndex: 1 },
      { question: 'Какое время "прошлое" в русском?', options: ['Настоящее', 'Будущее', 'Прошлое', 'Нет времени'], correctIndex: 2 },
      { question: 'Как сказать "привет" на русском?', options: ['Hello', 'Bonjour', 'Привет', 'Ciao'], correctIndex: 2 },
      { question: 'Какой цвет "красный" на русском?', options: ['Красный', 'Синий', 'Зеленый', 'Желтый'], correctIndex: 0 },
      { question: 'Какое число "пять" на русском?', options: ['Один', 'Два', 'Три', 'Пять'], correctIndex: 3 },
      { question: 'Как сказать "школа" на русском?', options: ['Школа', 'Университет', 'Работа', 'Дом'], correctIndex: 0 },
      { question: 'Какой день недели "понедельник"?', options: ['Понедельник', 'Вторник', 'Среда', 'Четверг'], correctIndex: 0 },
      { question: 'Как сказать "вода" на русском?', options: ['Вода', 'Хлеб', 'Мясо', 'Фрукты'], correctIndex: 0 },
    ],
  },
]

async function seedCourses() {
  const uri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/edutc'

  await mongoose.connect(uri)

  for (const course of courses) {
    await Course.findOneAndUpdate(
      { courseKey: course.courseKey },
      { $set: course },
      { upsert: true, returnDocument: 'after', runValidators: true }
    )
  }

  console.log(`Seeded ${courses.length} courses`)
  await mongoose.disconnect()
}

seedCourses().catch((error) => {
  console.error(error)
  process.exit(1)
})
